<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsMa3WK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsMa3WK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMsMa3WK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMsMa3WK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMsMa3WK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MsMa3WK',
    'container.build_id' => '86aa4731',
    'container.build_time' => 1649677820,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsMa3WK');
