index:
   path: /
   controller: App\Controller\AccueilController::index
   host: localhost

accueil:
   path: /accueil
   controller: App\Controller\AccueilController::index
   host: localhost

connexion:
   path: /login
   controller: App\Controller\SecurityController::login
   host: localhost

inscription:
   path: /inscription
   controller: App\Controller\InscriptionController::index
   host: localhost
   
compte:
   path: /compte
   controller: App\Controller\CompteController::index
   host: localhost

contact:
   path: /contact
   controller: App\Controller\ContactController::index
   host: localhost

propos:
   path: /propos
   controller: App\Controller\ProposController::index
   host: localhost 